# Generated by Django 4.2.2 on 2023-06-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('property_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('rooms_available', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('image_first', models.ImageField(blank=True, null=True, upload_to='property')),
                ('image_second', models.ImageField(blank=True, null=True, upload_to='property')),
                ('image_third', models.ImageField(blank=True, null=True, upload_to='property')),
                ('image_fourth', models.ImageField(blank=True, null=True, upload_to='property')),
            ],
        ),
    ]
